### ISSUE TITLE
Audio parameters are not sent on file loading

### ISSUE THREAD

**Issue by b2renger** [mgsx-dev/rainstick#1]
When loading a rainstick from a json file, audio parameters grouped in the sendMix and sendFormants functions are not sent to the audio engine.

**Comment by mgsx-dev** [comment]
I need to code a callback system after system settings has been loaded (new interface for systems)

**Comment by mgsx-dev** [comment]
for rainstick it's OK since we send all parameters at each frame.

But editor values are not updated, workaround for now is to close/open each system views.

I will fix it in KIT
